name: Docker Test
on: [push]
jobs:
  Build:
    runs-on: ubuntu-22.04
    container: ros:iron
    steps:
      - name: Test
        run: |
          env
          . /opt/ros/$ROS_DISTRO/setup.sh
          env
          python3 -c "import std_msgs; print(std_msgs.__file__)"
