name: Unit Tests

on:
  push:
    branches:
      - $default-branch
      # TODO: set develop as default
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:iron
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          cd $GITHUB_WORKSPACE
          apt update
          rosdep update
          rosdep install --from-paths ros2 --ignore-packages-from-source --verbose --default-yes --skip-keys="aduulm_cmake_tools aduulm_messages"
      - name: Build orchestrator
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          cd $GITHUB_WORKSPACE
          colcon build --packages-up-to orchestrator
      - name: Run tests
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          cd $GITHUB_WORKSPACE
          . ./install/setup.sh
          pytest-3 ros2/orchestrator
